# Generated by Django 5.2.5 on 2025-08-15 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'در انتظار'), (2, 'تایید شده'), (3, 'رد شده')], default=1)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='credits_cre_status_fc3c2a_idx'), models.Index(fields=['vendor', 'status'], name='credits_cre_vendor__e3aaab_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='credit_amount_positive')],
            },
        ),
    ]
