# Generated by Django 5.2.5 on 2025-08-15 14:15

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='charge amount')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='vendors.vendor', verbose_name='vendor charge')),
            ],
            options={
                'verbose_name': 'charge',
                'verbose_name_plural': 'charges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', '-created_at'], name='charges_cha_vendor__5bee2b_idx'), models.Index(fields=['phone_number', '-created_at'], name='charges_cha_phone_n_a4b3b1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='charge_amount_positive')],
            },
        ),
    ]
