# Generated by Django 5.2.5 on 2025-08-15 14:15

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.IntegerField(choices=[(1, 'افزایش اعتبار'), (2, 'فروش شارژ')])),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.IntegerField(choices=[(1, 'در انتظار'), (2, 'تایید شده'), (3, 'رد شده')], default=1)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_successful', models.BooleanField(default=True)),
                ('credit_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credits.creditrequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'created_at'], name='transaction_vendor__2f54a5_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_09d7ec_idx'), models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx')],
            },
        ),
    ]
