# Generated by Django 5.2.5 on 2025-08-15 14:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Vendor Name')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='vendors_ven_is_acti_45ad2b_idx'), models.Index(fields=['balance'], name='vendors_ven_balance_7c9747_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='vendor_balance_non_negative'), models.CheckConstraint(condition=models.Q(('daily_limit__gte', 0)), name='vendor_daily_limit_non_negative')],
            },
        ),
    ]
